# syntax=docker/dockerfile:1
FROM archlinux:latest

LABEL group="arch-dns-server"
LABEL group.role="arch-dns-server-master"


RUN pacman -Sy --noconfirm vi openssl


# COPY setup-service.sh /setup-service.sh


# CMD ["cd", "/", "&&", "./setup-service.sh", ">", "./setup-service.log"]
