name: caauthority

services:
  caauthority:
    build: .
    tty: true
    stdin_open: true
    container_name: caauthority
    hostname: caauthority.jai.net
    networks:
      jai_net:
        ipv4_address: 172.28.0.11
    
    # ports:
    #   - "80:80"
    # depends_on:
    #   - db
    # command: tail -f /dev/null &
    # command: /bin/bash -c "sleep infinity"

networks:
  jai_net:
    external: true

